
title: 윤슬케어
email: 이메일이다...
description: >-
  윤슬케어 설명글
baseurl: ""
url: ""
naver_blog: http://rss.blog.naver.com/nvr_design.xml

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from

repository:

collections:
  notices:
    output: true
    permalink: /notice/:name

sass:
   sass_dir: bower_components/bootstrap/scss

# Exclude from processing.
exclude:
  - bower_components

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

defaults:
  - scope:
      path: ""
      type: "notices"
    values:
      layout: "pages"
