
title: 윤슬케어
email: hello@yunseul-care.com
description: >-
  윤슬케어 설명글
baseurl: ""
url: ""

facebook: https://www.facebook.com/yunseulcare
instagram: https://www.instagram.com/yunseulcare/
naver_blog: https://blog.naver.com/yunseul_care

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from

repository: ictact-coop/yuenseul-care

collections:
  notices:
    output: true
    permalink: /notice/:name

sass:
   sass_dir: bower_components/bootstrap/scss

# Exclude from processing.
exclude:
  - bower_components

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "en"
    values:
      lang: "en"
