title: 주식회사 윤슬케어
address: 03992 서울특별시 마포구 월드컵북로 6길 36번지 (동교동 203-4), 5층
byline: 사업자등록번호 641-86-01236 | 대표이사 정승훈
copyright: Copyright © YUNSEUL CARE Inc. All rights reserved.
facebook_url: https://www.facebook.com/yunseulcare
instagram_url: https://www.instagram.com/yunseulcare/
naver_blog_url: https://blog.naver.com/yunseul_care
